//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSN.Web.Portal.Resources.Home {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LibroReclamacionResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal LibroReclamacionResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSN.Web.Portal.Resources.Home.LibroReclamacionResource", typeof(LibroReclamacionResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Materno (*).
        /// </summary>
        public static string EtiquetaApellidoMaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido Paterno (*).
        /// </summary>
        public static string EtiquetaApellidoPaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Ejercicio de los derechos ARCO.
        /// </summary>
        public static string EtiquetaARCO {
            get {
                return ResourceManager.GetString("EtiquetaARCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Autorizo la notificación del resultado del reclamo al correo electrónico consignado..
        /// </summary>
        public static string EtiquetaAutorizoEmail {
            get {
                return ResourceManager.GetString("EtiquetaAutorizoEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Celular o Teléfono.
        /// </summary>
        public static string EtiquetaCelularTelefono {
            get {
                return ResourceManager.GetString("EtiquetaCelularTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Consecuencias de proporcionar los datos o su negativa a hacerlo.
        /// </summary>
        public static string EtiquetaConsecuencias {
            get {
                return ResourceManager.GetString("EtiquetaConsecuencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Puede ejercer sus derechos de acceso, rectificación, cancelación, oposición, así como revocar su consentimiento para el uso de sus datos, cuando corresponda, dirigiéndose al Instituto Nacional de Salud del Niño – Breña. Puede hacerlo presencialmente en Av. Brasil 600 Breña - Lima, o mediante correo electrónico a libroreclamacion@insn.gob.pe..
        /// </summary>
        public static string EtiquetaContextoARCO {
            get {
                return ResourceManager.GetString("EtiquetaContextoARCO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a En caso de no proporcionar la información obligatoria marcada con (*) no será posible ofrecerle el servicio de atención médica..
        /// </summary>
        public static string EtiquetaContextoConsecuencias {
            get {
                return ResourceManager.GetString("EtiquetaContextoConsecuencias", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Con el fin de cumplir con los objetivos mencionados en esta política de privacidad, es necesario que nos facilite la siguiente información: Datos identificativos, que incluyen nombres, apellidos, número de documento nacional de identidad, carné de extranjería, dirección de domicilio, número de teléfono y dirección de correo electrónico. Además, datos de características personales como estado civil, fecha de nacimiento, nacionalidad, género y detalles de la persona de contacto. También se incluyen datos sens [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EtiquetaContextoDatosObligatorios {
            get {
                return ResourceManager.GetString("EtiquetaContextoDatosObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a La información personal que comparta con nosotros será empleada para administrar comentarios y reclamaciones, abordar cualquier inconveniente y reconocer oportunidades de mejora en relación con nuestros servicios de atención médica.
        /// </summary>
        public static string EtiquetaContextoFinalidad {
            get {
                return ResourceManager.GetString("EtiquetaContextoFinalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Instituto Nacional de Salud del Niño, con RUC N° 20131368403, y con domicilio en Av. Brasil 600 Breña- Lima - Lima.
        /// </summary>
        public static string EtiquetaContextoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaContextoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se conservará sus datos personales por un plazo indeterminado o superior a un (01) año..
        /// </summary>
        public static string EtiquetaContextoTiempo {
            get {
                return ResourceManager.GetString("EtiquetaContextoTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Se efectúa la transferencia de datos personales a nivel nacional hacia otra entidad pública, específicamente a la Superintendencia Nacional de Salud (SUSALUD) , no se lleva a cabo la transferencia de datos personales a nivel internacional..
        /// </summary>
        public static string EtiquetaContextoTransferencia {
            get {
                return ResourceManager.GetString("EtiquetaContextoTransferencia", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos personales obligatorios.
        /// </summary>
        public static string EtiquetaDatosObligatorios {
            get {
                return ResourceManager.GetString("EtiquetaDatosObligatorios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Datos del Paciente.
        /// </summary>
        public static string EtiquetaDatosPaciente {
            get {
                return ResourceManager.GetString("EtiquetaDatosPaciente", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dirección.
        /// </summary>
        public static string EtiquetaDirección {
            get {
                return ResourceManager.GetString("EtiquetaDirección", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nro. Documento (*).
        /// </summary>
        public static string EtiquetaDocumentoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo electrónico  (*).
        /// </summary>
        public static string EtiquetaEmail {
            get {
                return ResourceManager.GetString("EtiquetaEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Finalidad.
        /// </summary>
        public static string EtiquetaFinalidad {
            get {
                return ResourceManager.GetString("EtiquetaFinalidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Identidad y domicilio.
        /// </summary>
        public static string EtiquetaIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Adjuntar imagen.
        /// </summary>
        public static string EtiquetaImagen {
            get {
                return ResourceManager.GetString("EtiquetaImagen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombres (*).
        /// </summary>
        public static string EtiquetaNombres {
            get {
                return ResourceManager.GetString("EtiquetaNombres", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Razón Social (*).
        /// </summary>
        public static string EtiquetaRazonSocial {
            get {
                return ResourceManager.GetString("EtiquetaRazonSocial", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reclamo (*).
        /// </summary>
        public static string EtiquetaReclamo {
            get {
                return ResourceManager.GetString("EtiquetaReclamo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a RUC (*).
        /// </summary>
        public static string EtiquetaRUC {
            get {
                return ResourceManager.GetString("EtiquetaRUC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Registro del Libro de Reclamaciones en Salud Web.
        /// </summary>
        public static string EtiquetaSeccion {
            get {
                return ResourceManager.GetString("EtiquetaSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tiempo.
        /// </summary>
        public static string EtiquetaTiempo {
            get {
                return ResourceManager.GetString("EtiquetaTiempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Documento.
        /// </summary>
        public static string EtiquetaTipoDocumentoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Parentesco.
        /// </summary>
        public static string EtiquetaTipoParentesco {
            get {
                return ResourceManager.GetString("EtiquetaTipoParentesco", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Persona.
        /// </summary>
        public static string EtiquetaTipoPersona {
            get {
                return ResourceManager.GetString("EtiquetaTipoPersona", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Libro de Reclamaciones en Salud.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Transferencia.
        /// </summary>
        public static string EtiquetaTransferencia {
            get {
                return ResourceManager.GetString("EtiquetaTransferencia", resourceCulture);
            }
        }
    }
}
