//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSN.Web.Portal.Resources.SegApp.Mantenimiento {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsuarioResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsuarioResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSN.Web.Portal.Resources.SegApp.Mantenimiento.UsuarioResource", typeof(UsuarioResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido materno.
        /// </summary>
        public static string EtiquetaApellidoMaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoMaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Apellido paterno.
        /// </summary>
        public static string EtiquetaApellidoPaterno {
            get {
                return ResourceManager.GetString("EtiquetaApellidoPaterno", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre o usuario.
        /// </summary>
        public static string EtiquetaBusqueda {
            get {
                return ResourceManager.GetString("EtiquetaBusqueda", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Contraseña.
        /// </summary>
        public static string EtiquetaClave {
            get {
                return ResourceManager.GetString("EtiquetaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirmar contraseña.
        /// </summary>
        public static string EtiquetaConfirmaClave {
            get {
                return ResourceManager.GetString("EtiquetaConfirmaClave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EtiquetaCorreo {
            get {
                return ResourceManager.GetString("EtiquetaCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Documento de identidad.
        /// </summary>
        public static string EtiquetaDocumentoIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaDocumentoIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Correo.
        /// </summary>
        public static string EtiquetaGridCorreo {
            get {
                return ResourceManager.GetString("EtiquetaGridCorreo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Doc. Identidad.
        /// </summary>
        public static string EtiquetaGridDocIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaGridDocIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string EtiquetaGridNombre {
            get {
                return ResourceManager.GetString("EtiquetaGridNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string EtiquetaGridServicio {
            get {
                return ResourceManager.GetString("EtiquetaGridServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono(s).
        /// </summary>
        public static string EtiquetaGridTelefono {
            get {
                return ResourceManager.GetString("EtiquetaGridTelefono", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo Doc..
        /// </summary>
        public static string EtiquetaGridTipoDocIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaGridTipoDocIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string EtiquetaGridUsuario {
            get {
                return ResourceManager.GetString("EtiquetaGridUsuario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Id.
        /// </summary>
        public static string EtiquetaId {
            get {
                return ResourceManager.GetString("EtiquetaId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Nombre.
        /// </summary>
        public static string EtiquetaNombre {
            get {
                return ResourceManager.GetString("EtiquetaNombre", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a MANTENIMIENTO.
        /// </summary>
        public static string EtiquetaSeccion {
            get {
                return ResourceManager.GetString("EtiquetaSeccion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Servicio.
        /// </summary>
        public static string EtiquetaServicio {
            get {
                return ResourceManager.GetString("EtiquetaServicio", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teléfono 1.
        /// </summary>
        public static string EtiquetaTelefono1 {
            get {
                return ResourceManager.GetString("EtiquetaTelefono1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Teféfono 2.
        /// </summary>
        public static string EtiquetaTelefono2 {
            get {
                return ResourceManager.GetString("EtiquetaTelefono2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tipo documento identidad.
        /// </summary>
        public static string EtiquetaTipoDocIdentidad {
            get {
                return ResourceManager.GetString("EtiquetaTipoDocIdentidad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a USUARIO.
        /// </summary>
        public static string EtiquetaTitulo {
            get {
                return ResourceManager.GetString("EtiquetaTitulo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a EDITAR USUARIO.
        /// </summary>
        public static string EtiquetaTituloEditar {
            get {
                return ResourceManager.GetString("EtiquetaTituloEditar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a NUEVO USUARIO.
        /// </summary>
        public static string EtiquetaTituloNuevo {
            get {
                return ResourceManager.GetString("EtiquetaTituloNuevo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Usuario.
        /// </summary>
        public static string EtiquetaUsuario {
            get {
                return ResourceManager.GetString("EtiquetaUsuario", resourceCulture);
            }
        }
    }
}
