//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace INSN.Web.Portal.Resources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class NoticiaResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal NoticiaResource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("INSN.Web.Portal.Resources.NoticiaResource", typeof(NoticiaResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Noticia Nº066/2023.
        /// </summary>
        public static string EtiquetaContenidoNoticia_1_CodigoFecha {
            get {
                return ResourceManager.GetString("EtiquetaContenidoNoticia_1_CodigoFecha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a El Dr. Raffo Escalante Kanashiro, Jefe de la Oficina de Gestión de la Calidad del Instituto Nacional de Salud del Niño, participó en la mesa de trabajo “Importancia de la propuesta de Ley RCP (Reanimación Cardiopulmonar) para todos” organizada por la Congresista Milagros Jáuregui de Aguayo.
        ///.
        /// </summary>
        public static string EtiquetaContenidoNoticia_1_p1 {
            get {
                return ResourceManager.GetString("EtiquetaContenidoNoticia_1_p1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Esta propuesta es una iniciativa en la cual se quiere lograr que la respuesta inicial en reanimación cardiopulmonar (RCP), uso del desfibrilador externo automático (DEA) y Maniobra de Heimlich, sea un compromiso para todos basado en el entrenamiento y conocimiento a nivel de organizaciones, comunidad, colegios, universidades, establecimientos públicos y privados. &lt;br&gt;
        ///También participaron en la reunión el Dr. Tomy Villanueva del Hospital de Emergencias Pediátricas Grau y el Sr. Esteban Astete, representant [resto de la cadena truncado]&quot;;.
        /// </summary>
        public static string EtiquetaContenidoNoticia_1_p2 {
            get {
                return ResourceManager.GetString("EtiquetaContenidoNoticia_1_p2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Jue, 20/07/2023 - 12:00.
        /// </summary>
        public static string EtiquetaFechaNoticia_1 {
            get {
                return ResourceManager.GetString("EtiquetaFechaNoticia_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a INSN presente en mesa de trabajo sobre propuesta de Ley RCP para todos.
        /// </summary>
        public static string EtiquetaTítuloNoticia_1 {
            get {
                return ResourceManager.GetString("EtiquetaTítuloNoticia_1", resourceCulture);
            }
        }
    }
}
